### ISSUE TITLE
Multivariate ARCH Tracking

### ISSUE THREAD

**Issue by bashtage** [bashtage/arch#242]
Long-term plan to implement some multivariate GARCH models:

First Stage:
- [ ] Base classes
- [ ] Constant Covariance volatility
- [ ] Multivariate Normal distribution
- [ ] Constant Mean
Second Stage:
- [ ] VAR-X mean model
- [ ] VAR, LR, Constant Mean refactor, ZeroMean as special cases of VAR-X
Third Stage:
- [ ] Scalar BEKK with 1-step estimation
- [ ] Scalar BEKK with 2-step estimation 
- [ ] Scalar BEKK with 3-step estimation (targetting)
- [ ] Scalar BEKK with composite estimation (1, 2 and 3 step)
Fourth Stage:
- [ ] Multivariate Student's t distribution
Fifth Stage:
- [ ] Other BEKK and Matrix GARCH models
- [ ] DCC (1-step and 2-step, full and composite) and cDCC (1-, 2- and 3-step, full and composite)
- [ ] Other GARCH models (OGARCH, GO-GARCH??)

**Comment by Aniketsy** [comment]
hi @bashtage i'd like to help with this, do you have any preferred paper or reference for this implementation. Thanks!
