### ISSUE TITLE
ROADMAP: Future plans

### ISSUE THREAD

**Issue by bashtage** [bashtage/arch#351]
Some planned additions. No specific time for completion. 

- [ ] Engle-Granger Cointegration Testing
- [ ] Phillips-Ouliaris Cointegration Testing
- [ ] Dynamic OLS Cointegration Vector Estimation
- [ ] FM OLS Cointegration Vector Estimation
- [ ] CCR Cointegration Vector Estimation
- [ ] VAR-HAC
- [ ] Pre-whitened Recolored Long-run covariance estimation
- [ ] GARCH-X and EGARCH-X
- [ ] Univariate MA Mean Model
- [ ] Reduced memory in simulation-forecasting
- [ ] Generalized lag GARCH models (e.g., lag 2 but not 1)
- [ ] General support for variance targetted estimation
- [ ] Multivariate GARCH

**Comment by itsNH98** [comment]
Available to work on the Multivariate GARCH if it is still on the Roadmap

**Comment by elvinwangyh** [comment]
There is an implementation for DCC-GARCH in Python, perhaps you can join the effort https://github.com/Topaceminem/DCC-GARCH .

**Comment by premdev1234** [comment]
i would like  to work on the  Univariate MA Mean Model  if it is still on the Roadmap
